### ISSUE TITLE
Update to 1.21

### ISSUE THREAD

**Issue by PedrixzZ** [ShadowMC69/VulkanMod#24]

**Comment by Felix14-v2** [comment]
The original VulkanMod still has no 1.21 version, so this issue should be closed.

**Comment by NinjaLegendmc** [comment]
> The original VulkanMod still has no 1.21 version, so this issue should be closed.

Yeah 1.21 still not coming in original vk mod web page you can join shadows unofficial discord server in gethub page

**Comment by NinjaLegendmc** [comment]
![Screenshot_2024_0616_082926](https://github.com/SaintPlayzPH/VulkanMod/assets/170965489/a12eb7c0-805e-432f-992e-bf6e0587aa74)
