### ISSUE TITLE
Weird chunk delay when moving backwards 

### ISSUE THREAD

**Issue by Nekotaco** [ShadowMC69/VulkanMod#33]
https://github.com/SaintPlayzPH/VulkanMod/assets/128432906/fe5acde4-6c80-4c9e-b1c1-f35a6a695cca

I got this issue after trying 1.21 w your vkmod

Latest log if u need it :>
[latestlog.txt](https://github.com/user-attachments/files/15949902/latestlog.txt)

**Comment by Nekotaco** [comment]
https://github.com/SaintPlayzPH/VulkanMod/assets/128432906/969b0831-fc5a-4339-9575-014d74444273
 
It seems fine in vanilla,fresh install btw!
[latestlog.txt](https://github.com/user-attachments/files/15950054/latestlog.txt)

**Comment by NinjaLegendmc** [comment]
This bug sometimes appear in mine also
Note: vulkan now need fabric api for fluid rendering 
Try with fabric api if it won't work than join shadow discord for help!
https://discord.com/invite/4hv6SDG7Uh

**Comment by Nekotaco** [comment]
Oh wow it doesn't send any notification my bad.. anyways, the issue still happening even tho i already got fabric api.

**Comment by Nekotaco** [comment]
> This bug sometimes appear in mine also Note: vulkan now need fabric api for fluid rendering Try with fabric api if it won't work than join shadow discord for help! https://discord.com/invite/4hv6SDG7Uh

Oh wow it doesn't send any notification my bad.. anyways, the issue still happening even tho i already got fabric api.

**Comment by NinjaLegendmc** [comment]
> > This bug sometimes appear in mine also Note: vulkan now need fabric api for fluid rendering Try with fabric api if it won't work than join shadow discord for help! https://discord.com/invite/4hv6SDG7Uh
> 
> Oh wow it doesn't send any notification my bad.. anyways, the issue still happening even tho i already got fabric api.

Join this vk patch mod discord link https://discord.com/invite/CHX4dUSTqs
