### ISSUE TITLE
Minecraft crash due to HeadlessException on startup with VulkanMod on PojavLauncher

### ISSUE THREAD

**Issue by BlueGradientHorizon** [ShadowMC69/VulkanMod#56]
Hello. I was trying to dig some information on if there is any method/hack-fix/modification to run VulkanMod on PojavLauncher, and I found your fork with `pojav` branch in it, so it gave me some hope. I just don't know where else to ask, because both Pojav and VulkanMod teams are tired from countless questions about running rendering optimization mods on android devices. I've also seen your comparison video on YT, so I assume it is actually possible to launch.

My device:
- Model: POCO F5 [marble] 12/256 (23049PCD8G)
- OS: stock HyperOS 1.0.6.0 UMRMIXM (A14, UKQ1.230804.001)
- Kernel: custom 5.10.222-SilverCore-01974-g8090c585658b
- Adreno GPU driver: custom with VK API 1.3 support, see [report on vulkan.gpuinfo.org](https://vulkan.gpuinfo.org/displayreport.php?id=32836)

Mod used: artifact from latest CI build on branch `pojav`.
[See `latestlog.txt` with HeadlessException](https://mclo.gs/PIYUpai)

This exception happens with any type of renderer Pojav supports: GL4ES, Zink (with "Use system Vulkan driver" enabled also no difference) and ANGLE. Did you ever encountered such problem? If yes, what did you do to solve it? If no, maybe you have any thoughts on why does this happening, why the graphics environment is becoming headless every time I try to start game when VMod in mods directory?

Thanks.

**Comment by Felix14-v2** [comment]
You just used wrong Minecraft version:
```
[21:42:24] [main/ERROR]: Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace 'Minecraft' (minecraft) 1.21.1 with version 1.20.3 or version 1.20.4.
More details:
	 - Mod 'VulkanMod' (vulkanmod) 0.4.7_dev requires version 1.20.3 or version 1.20.4 of 'Minecraft' (minecraft), but only the wrong version is present: 1.21.1!
```

Source code of VulkanMod for Minecraft 1.20.5+ isn't still publically available, so 1.20.4 is the limit here (although there are some experiments in Shadow discord)
